[api_keys]
OPENAI_API_KEY = "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"
HUGGINGFACE_API_KEY = "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"
OPENAI_API_KEY_leire = "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"